from typing import Protocol, Any, Optional

class CacheBackend(Protocol):

    def get(self, key: str) -> Optional[Any]: ...

    def set(self, key: str, value: Any) -> None: ...

    def delete(self, key: str) -> None: ...

    def clear(self) -> None: ...
