from typing import Optional, List, Protocol
from core.models import FeatureFlag

class FlagRepository(Protocol):

    def get_flag(self, name: str) -> Optional[FeatureFlag]: ...

    def get_all_flags(self) -> List[FeatureFlag]: ...

    def save_flag(self, flag: FeatureFlag) -> FeatureFlag: ...

    def update_flag(self, name: str, enabled: bool) -> FeatureFlag: ...

    def get_override(self, flag_name: str, override_type: str, value: str) -> Optional[bool]: ...

    def set_override(self, flag_name: str, override_type: str, value: str, enabled: bool) -> None: ...

    def delete_override(self, flag_name: str, override_type: str, value: str) -> None: ...